stages:
  - test
  - dist
  - deploy
  - release

variables:
  GIT_DEPTH: 100
  GIT_SUBMODULE_STRATEGY: recursive

# --- Stage Templates ----------------------------------------------------------

.test: &test
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_STAGE}
    paths:
    - build
  before_script:
    - $python -m pip install -U pip
    - $python -m pip install -U -r .github/workflows/requirements.txt
  script:
    - $python setup.py build_clib --debug
    - $python setup.py build_ext  --debug --inplace
    - $python -m coverage run -m unittest discover -v

.test-cpython: &test-cpython
  image: quay.io/pypa/manylinux2010_x86_64
  artifacts:
    reports:
      coverage_report:
          coverage_format: cobertura
          path: coverage.xml
  after_script:
    - $python -m coverage xml
    - $python -m coverage report
    - $python -m codecov
  <<: *test

.test-pypy: &test-pypy
  image: pypywheels/manylinux2010-pypy_x86_64:2020-12-11-f1e0e80
  <<: *test


.bdist: &bdist
  stage: dist
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_STAGE}
    paths:
    - build
  artifacts:
    paths:
      - dist/*.whl
  only:
    - tags
  before_script:
    - $python -m pip install -U -r .github/workflows/requirements.txt
  script:
    - $python setup.py build_clib
    - $python setup.py build_ext  --inplace
    - $python -m unittest discover -v
    - $python setup.py bdist_wheel

.bdist-cpython: &bdist-cpython
  image: quay.io/pypa/manylinux2010_x86_64
  <<: *bdist

.bdist-pypy: &bdist-pypy
  image: pypywheels/manylinux2010-pypy_x86_64:2020-12-11-f1e0e80
  <<: *bdist


# --- Stages -------------------------------------------------------------------

test:python3.6:
  variables:
    python: /opt/python/cp36-cp36m/bin/python
  <<: *test-cpython

test:python3.7:
  variables:
    python: /opt/python/cp37-cp37m/bin/python
  <<: *test-cpython

test:python3.8:
  variables:
    python: /opt/python/cp38-cp38/bin/python
  <<: *test-cpython

test:python3.9:
  variables:
    python: /opt/python/cp39-cp39/bin/python
  <<: *test-cpython

test:python3.10:
  variables:
    python: /opt/python/cp310-cp310/bin/python
  <<: *test-cpython

test:pypy3.6:
  variables:
    python: /opt/pypy/pypy3.6-7.3.3/bin/python
  <<: *test-pypy

test:pypy3.7:
  variables:
    python: /opt/pypy/pypy3.7-7.3.3/bin/python
  <<: *test-pypy


# sdist:
#   variables:
#     python: /opt/python/cp39-cp39/bin/python
#   image: quay.io/pypa/manylinux2010_x86_64
#   stage: dist
#   only:
#     - tags
#   artifacts:
#     paths:
#       - dist/*.tar.gz
#   before_script:
#     - $python -m pip install -U -r .github/workflows/requirements.txt
#   script:
#     - $python setup.py sdist
#     - $python -m pip install pyhmmer dist/*.tar.gz
#
# bdist:python3.6:
#   variables:
#     python: /opt/python/cp36-cp36m/bin/python
#   <<: *bdist-cpython
#
# bdist:python3.7:
#   variables:
#     python: /opt/python/cp37-cp37m/bin/python
#   <<: *bdist-cpython
#
# bdist:python3.8:
#   variables:
#     python: /opt/python/cp38-cp38/bin/python
#   <<: *bdist-cpython
#
# bdist:python3.9:
#   variables:
#     python: /opt/python/cp39-cp39/bin/python
#   <<: *bdist-cpython
#
# bdist:pypy3.6:
#   variables:
#     python: /opt/pypy/pypy3.6-7.3.3/bin/python
#   <<: *bdist-pypy
#
# bdist:pypy3.7:
#   variables:
#     python: /opt/pypy/pypy3.7-7.3.3/bin/python
#   <<: *bdist-pypy
#
#
# twine:
#   variables:
#     python: /opt/python/cp39-cp39/bin/python
#   image: quay.io/pypa/manylinux2010_x86_64
#   stage: deploy
#   only:
#     - tags
#   dependencies:
#     - sdist
#     - bdist:python3.6
#     - bdist:python3.7
#     - bdist:python3.8
#     - bdist:python3.9
#     - bdist:pypy3.6
#     - bdist:pypy3.7
#   before_script:
#     - $python -m pip install -U auditwheel twine
#   script:
#       - for whl in dist/*.whl; do auditwheel repair "$whl" -w dist && rm "$whl"; done
#       - $python -m twine upload dist/*
#
# release:
#   image: ruby
#   stage: release
#   only:
#     - tags
#   before_script:
#     - gem install chandler
#   script:
#     - chandler push --github="althonos/pyhmmer" --changelog="CHANGELOG.md"
